### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by mzch** [rockmanvnx6/FireShare#24]
I setup FireShare, but can't register me. It says, "Sorry, email is already in use." and no collections aren't created in MongoDB.
How can I migrate database?

**Comment by rockmanvnx6** [comment]
@mzch Hi, I think you're still using my database. change your MongoDB URL at: `backend/.env`. The project uses MongoDB Atlas for database but it will work on a local MongoDB as well. 

Let me know if it solves the issue.

**Comment by mzch** [comment]
Thanks for your reply, @rockmanvnx6 
I set `DB_CONNECT = mongodb://fireshare:password@localhost:27017/fireshare` in .env
but still unable.

**Comment by rockmanvnx6** [comment]
@mzch could you provide browser log as well as the terminal log?

**Comment by mzch** [comment]
<img width="552" alt="ScreenShot 2019-11-30 13 02 40" src="https://user-images.githubusercontent.com/621178/69895391-c7a60580-1371-11ea-8c48-657ddbb1f37b.png">

Is it necessary to rewrite src/Constants.js?

**Comment by rockmanvnx6** [comment]
it looks like your frontend can't talk to backend. If your backend is running on a different port, yes you might have to change the link in `constant.js`

**Comment by mzch** [comment]
Well, the backend process can still accept in port 5000. It seems that my browser tries to connect localhost:5000 and fails...

**Comment by rockmanvnx6** [comment]
The browser is trying to send `OPTION` message to the server but it refuses it. This might be something to do with CORS or could be another thing that caused it. However the code should be configured with cors.

What I would suggest you to do is running of `nodemon server` instead of `node server` for debugging you can install `nodemon` if you don't have it.

I reran the script locally, it works fine with the original MongoDB link. Does the issue only happen when you run off your local MongoDB database?

**Comment by mzch** [comment]
I'm running FireShare on my remote server in U.S. and I try to connect to it from my Mac in JP.
Is it OK separately?

**Comment by mzch** [comment]
Hi,
I rewrite frontend/src/Constrants.js, `export const API_URL = 'https://api.upldx.com'`
and proxied to localhost:5000, then got success. Thanks!

**Comment by rockmanvnx6** [comment]
Yes because they are in different countries so not `local` anymore to be called `localhost` :)

I'm glad that it works, will close the issue now. Feel free to open it if you still have any issues.
